build-deploy:
  only:
    - master
    - gitlab
  tags:
    - mozmeao
  variables:
    DOCKER_TAG: meao-perf-dashboard:latest
  script:
    - docker build --pull -t "$DOCKER_TAG" .
    - docker run -i --rm -e NETLIFY_AUTH_TOKEN -e NETLIFY_SITE_ID -e WPT_API_KEY "$DOCKER_TAG"
    - curl -s ${DMS_URL}
